# Generated by Django 3.1.1 on 2020-10-20 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teams',
        ),
    ]
