# Generated by Django 3.1.1 on 2020-10-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='display_name',
            field=models.CharField(default='', max_length=254),
        ),
    ]
