# Generated by Django 3.1.1 on 2020-10-25 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0017_auto_20201025_2004'),
        ('teams', '0005_remove_teams_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='hackathons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hackathon.hackathon'),
        ),
    ]
