# Generated by Django 3.1.1 on 2020-10-26 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_auto_20201026_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='team_name',
        ),
    ]
