# Generated by Django 3.1.1 on 2020-10-26 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0017_auto_20201025_2004'),
        ('teams', '0008_remove_teams_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='team_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hackathon.hackteam'),
        ),
    ]
