# Generated by Django 3.1.1 on 2020-10-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_teams_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='team_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
