# Generated by Django 3.1.1 on 2020-10-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_auto_20201026_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='teams',
            name='team_members',
        ),
        migrations.AddField(
            model_name='teams',
            name='team_members',
            field=models.ManyToManyField(to='teams.Team_members'),
        ),
    ]
