# Generated by Django 3.1.1 on 2020-10-26 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_auto_20201026_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_members',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
