# Generated by Django 3.1.1 on 2020-10-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_auto_20201026_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_members',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='team_members',
            field=models.ManyToManyField(to='teams.Team_Members'),
        ),
    ]
