# Generated by Django 3.1.1 on 2020-10-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0014_auto_20201026_2242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team_members',
            options={'verbose_name_plural': 'Team_Members'},
        ),
        migrations.AlterModelOptions(
            name='teams',
            options={'verbose_name_plural': 'Teams'},
        ),
        migrations.AlterField(
            model_name='team_members',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='team_members',
            field=models.ManyToManyField(related_name='teams', to='teams.Team_Members'),
        ),
    ]
