# Generated by Django 3.1.1 on 2020-10-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0015_auto_20201027_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='team_members',
            field=models.ManyToManyField(related_name='teams', to='teams.Team_Members'),
        ),
    ]
