# Generated by Django 3.1.1 on 2020-10-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0017_auto_20201027_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_members',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.RemoveField(
            model_name='teams',
            name='team_members',
        ),
        migrations.AddField(
            model_name='teams',
            name='team_members',
            field=models.ManyToManyField(blank=True, null=True, to='teams.Team_Members'),
        ),
    ]
