# Generated by Django 3.1.1 on 2020-10-27 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0019_auto_20201027_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='team_members',
        ),
        migrations.AddField(
            model_name='teams',
            name='team_members',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.team_members'),
        ),
    ]
