# Generated by Django 3.1.1 on 2020-10-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0022_auto_20201027_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='team_members',
            field=models.ManyToManyField(to='teams.Team_Members'),
        ),
    ]
