# Generated by Django 3.1.1 on 2020-12-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0027_auto_20201028_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='team_members',
            field=models.ManyToManyField(to='teams.Team_Members'),
        ),
    ]
