# Generated by Django 3.1.1 on 2020-12-09 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0029_auto_20201209_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='team_members',
        ),
        migrations.DeleteModel(
            name='Team_members',
        ),
        migrations.DeleteModel(
            name='Teams',
        ),
    ]
