# Generated by Django 3.1.1 on 2020-10-28 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0017_auto_20201025_2004'),
        ('hackathon', '0020_merge_20201026_2056'),
    ]

    operations = [
    ]
