# Generated by Django 3.1.1 on 2020-12-06 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0024_auto_20201103_2114'),
        ('hackathon', '0021_merge_20201028_0850'),
    ]

    operations = [
    ]
